### PR TITLE
Remove Booster parent

### PR DESCRIPTION
**Pull request by geoand**
Relates to: SB-1318

### CODE REVIEW

**Comment by geoand** [comment]
I am not really sure what went wrong here, @gytis would you mind taking a look?

**Comment by gytis** [comment]
Sure leave it with me, I'll take a look a bit later. I have been having issues with the messaging booster IT myself.

**Comment by geoand** [comment]
Thanks @gytis !

**Comment by geoand** [comment]
Closing since @gytis is looking into changes to this booster anyway

**Pull request closed without merging**
